shell:
  program: /opt/homebrew/bin/zsh
  args:
    - -c
    - "/opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux"

key_bindings:
  - { key: T, mods: Command,       chars: "\x11\x63" }
  - { key: D, mods: Command,       chars: "\x11\x25" }
  - { key: D, mods: Command|Shift, chars: "\x11\x22" }
  - { key: W, mods: Command,       chars: "\x11\x78" }  # Cmd+wでペインを削除する

window:
  title: Just do it!
  opacity: 0.8
  padding:
    x: 5
    y: 0
    dynamic_pading: false

cursor:
  style:
    shape: Beam
    blinking: Always
  vi_mode_style:
    shape: Beam
  blink_interval: 500

font:
  size: 14
  normal:
    family: Ricty
    style: Regular
  bold:
    family: Ricty
    style: Bold

#====================
# Color Scheme
# Document: https://github.com/alacritty/alacritty/wiki/Color-schemes
#====================
schemes:
  iceberg: &iceberg
    # Default colors
    primary:
      background: '#161821'
      foreground: '#d2d4de'

    # Normal colors
    normal:
      black:   '#161821'
      red:     '#e27878'
      green:   '#b4be82'
      yellow:  '#e2a478'
      blue:    '#84a0c6'
      magenta: '#a093c7'
      cyan:    '#89b8c2'
      white:   '#c6c8d1'

    # Bright colors
    bright:
      black:   '#6b7089'
      red:     '#e98989'
      green:   '#c0ca8e'
      yellow:  '#e9b189'
      blue:    '#91acd1'
      magenta: '#ada0d3'
      cyan:    '#95c4ce'
      white:   '#d2d4de'

colors: *iceberg
