# ====================
# Taps
# ====================
tap "d-kuro/tap", trusted: { formula: ["gwq"] }
tap "dagger/tap", trusted: { cask: ["container-use"] }
tap "FelixKratz/formulae", trusted: { formula: ["borders", "sketchybar"] }
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "leoafarias/fvm", trusted: { formula: ["fvm"] }
tap "nikitabobko/tap", trusted: { cask: ["aerospace"] }
tap "oven-sh/bun", trusted: { formula: ["bun"] }
tap "timac/vpnstatus", trusted: { formula: ["vpnutil"], cask: ["vpnstatus"] }

# ====================
# Formulae (CLI tools)
# ====================
brew "awscli"
brew "bat"
brew "borders"
brew "btop"
brew "bun"
brew "cocoapods"
brew "composer"
brew "container-use"
brew "curl"
brew "deno"
brew "git-delta"
brew "direnv"
brew "docker-compose"
brew "eza"
brew "fastfetch"
brew "figlet"
brew "fzf"
brew "ghq"
brew "git"
brew "gwq"
brew "jq"
brew "just"
brew "mas"
brew "mcat"
brew "ni"
brew "nkf"
brew "nvim"
brew "php@8.2"
brew "posting"
brew "rust"
brew "sheldon"
brew "starship"
brew "tfenv"
brew "tmux"
brew "tree"
brew "tty-clock"
brew "vim"
brew "volta"
brew "vpnutil"
brew "wasmtime"
brew "watch"
brew "wget"
brew "yazi"
brew "yq"
brew "zrok"
brew "zsh"

# ====================
# Casks (GUI apps)
# ====================
cask "1password"
cask "aerospace"
cask "android-studio"
cask "appcleaner"
cask "arc"
cask "bitwarden"
cask "claude-code"
cask "container"
cask "deskpad"
cask "dockdoor"
cask "docker"
cask "firefox"
cask "flutter"
cask "font-hack-nerd-font"
cask "font-hackgen-nerd"
cask "ghostty"
cask "google-cloud-sdk"
cask "google-chrome"
cask "google-japanese-ime"
cask "ngrok"
cask "obsidian"
cask "orbstack"
cask "omnigraffle"
cask "postman"
cask "raycast"
cask "slack"
cask "spacedrive"
cask "stoplight-studio"
cask "visual-studio-code"
cask "vpnstatus"
cask "zoom"
